#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" ::: 0
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 14
#pragma line 145 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 401 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 10 "<command line>" 2 ::: 200
#pragma line 1 "<built-in>" 2 ::: 201
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 2 ::: 202
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 1 ::: 224
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/hls_stream.h" 1 ::: 252
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 319
#pragma line 67 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/hls_stream.h" 2 ::: 448
#pragma line 28 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 2 ::: 543
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 544
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 573
#pragma line 122 "/usr/include/features.h" 3 4 ::: 669
#pragma line 146 "/usr/include/features.h" 3 4 ::: 686
#pragma line 177 "/usr/include/features.h" 3 4 ::: 695
#pragma line 326 "/usr/include/features.h" 3 4 ::: 722
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 759
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 805
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 823
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 829
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 833
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 843
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 847
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 857
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 894
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 935
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 945
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 948
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 965
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 966
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 968
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 969
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 994
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 999
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 1001
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 1006
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 1011
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 1012
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 1013
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 1020
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 1047
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 1049
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 1076
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 1077
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1097
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 1101
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 1126
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 1130
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 1156
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 1161
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 1179
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1180
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 1182
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 1190
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 1192
#pragma line 71 "/usr/include/math.h" 3 4 ::: 1198
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1199
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1564
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1575
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1576
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1941
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1942
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1943
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 2308
#pragma line 156 "/usr/include/math.h" 3 4 ::: 2309
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2367
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2369
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2371
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2377
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2379
#pragma line 355 "/usr/include/math.h" 3 4 ::: 2447
#pragma line 372 "/usr/include/math.h" 3 4 ::: 2449
#pragma line 392 "/usr/include/math.h" 3 4 ::: 2453
#pragma line 414 "/usr/include/math.h" 3 4 ::: 2468
#pragma line 472 "/usr/include/math.h" 3 4 ::: 2518
#pragma line 29 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 2 ::: 2520
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2531
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2566
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2602
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 2605
#pragma line 95 "/usr/include/string.h" 3 4 ::: 2643
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2712
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 2756
#pragma line 198 "/usr/include/string.h" 3 4 ::: 2783
#pragma line 211 "/usr/include/string.h" 3 4 ::: 2785
#pragma line 235 "/usr/include/string.h" 3 4 ::: 2787
#pragma line 262 "/usr/include/string.h" 3 4 ::: 2792
#pragma line 314 "/usr/include/string.h" 3 4 ::: 2822
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2827
#pragma line 436 "/usr/include/string.h" 3 4 ::: 2909
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2940
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2946
#pragma line 646 "/usr/include/string.h" 3 4 ::: 3037
#pragma line 39 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 2 ::: 3039
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3040
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3074
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3099
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3102
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 3112
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 3142
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 3143
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 3200
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3201
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3239
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3241
#pragma line 60 "/usr/include/endian.h" 3 4 ::: 3245
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 3248
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 3268
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3269
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 3271
#pragma line 55 "/usr/include/bits/byteswap.h" 3 4 ::: 3274
#pragma line 67 "/usr/include/bits/byteswap.h" 3 4 ::: 3276
#pragma line 100 "/usr/include/bits/byteswap.h" 3 4 ::: 3279
#pragma line 62 "/usr/include/endian.h" 2 3 4 ::: 3281
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 3282
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 3316
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 3322
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 3327
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3329
#pragma line 308 "/usr/include/stdlib.h" 3 4 ::: 3506
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3520
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 3551
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3580
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 3582
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 3609
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 3638
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 3645
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 3664
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 3667
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 3669
#pragma line 31 "/usr/include/sys/types.h" 2 3 4 ::: 3731
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3825
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3826
#pragma line 59 "/usr/include/time.h" 3 4 ::: 3848
#pragma line 75 "/usr/include/time.h" 3 4 ::: 3851
#pragma line 91 "/usr/include/time.h" 3 4 ::: 3854
#pragma line 103 "/usr/include/time.h" 3 4 ::: 3857
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3860
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3875
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3900
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3903
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3913
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3948
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3980
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4004
#pragma line 24 "/usr/include/bits/select.h" 2 3 4 ::: 4006
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 4007
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 4011
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 4053
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4064
#pragma line 118 "/usr/include/time.h" 3 4 ::: 4086
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 4094
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 4096
#pragma line 73 "/usr/include/bits/time.h" 3 4 ::: 4119
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 4127
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 4210
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 4214
#pragma line 64 "/usr/include/sys/sysmacros.h" 3 4 ::: 4254
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4256
#pragma line 263 "/usr/include/sys/types.h" 3 4 ::: 4278
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4288
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4312
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4314
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4315
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4334
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4353
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4422
#pragma line 272 "/usr/include/sys/types.h" 2 3 4 ::: 4453
#pragma line 321 "/usr/include/stdlib.h" 2 3 4 ::: 4457
#pragma line 470 "/usr/include/stdlib.h" 3 4 ::: 4599
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4628
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4654
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4679
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4682
#pragma line 498 "/usr/include/stdlib.h" 2 3 4 ::: 4697
#pragma line 630 "/usr/include/stdlib.h" 3 4 ::: 4821
#pragma line 652 "/usr/include/stdlib.h" 3 4 ::: 4835
#pragma line 684 "/usr/include/stdlib.h" 3 4 ::: 4859
#pragma line 706 "/usr/include/stdlib.h" 3 4 ::: 4872
#pragma line 964 "/usr/include/stdlib.h" 3 4 ::: 5121
#pragma line 40 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 2 ::: 5123
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 5124
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5159
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5184
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 5187
#pragma line 44 "/usr/include/stdio.h" 3 4 ::: 5188
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 5195
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 5198
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 5199
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 5232
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5248
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5273
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 5276
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 5281
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 5304
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 5325
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 5328
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 5340
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 5350
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 5357
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 5359
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 5363
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 5412
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 5413
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 5415
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 5421
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 5423
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 5447
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 5458
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 5499
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 5501
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 5523
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 5583
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 5598
#pragma line 552 "/usr/include/libio.h" 3 4 ::: 5610
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 5612
#pragma line 108 "/usr/include/stdio.h" 3 4 ::: 5618
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 5673
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 5691
#pragma line 204 "/usr/include/stdio.h" 3 4 ::: 5725
#pragma line 296 "/usr/include/stdio.h" 3 4 ::: 5802
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 5946
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 5966
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 6210
#pragma line 813 "/usr/include/stdio.h" 3 4 ::: 6221
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 6258
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 6291
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 6359
#pragma line 938 "/usr/include/stdio.h" 3 4 ::: 6362
#pragma line 41 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" 2 ::: 6364
#pragma line 54 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/src/correlation_accel_v1.hpp" ::: 6368
#pragma line 22 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_standard_alone/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 2 ::: 6393
