// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _mmult_accel_HH_
#define _mmult_accel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "mmult_accel_fadd_32ns_32ns_32_9_full_dsp.h"
#include "mmult_accel_fmul_32ns_32ns_32_5_max_dsp.h"

namespace ap_rtl {

struct mmult_accel : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<32> > in_A_Addr_A;
    sc_out< sc_logic > in_A_EN_A;
    sc_out< sc_lv<4> > in_A_WEN_A;
    sc_out< sc_lv<32> > in_A_Din_A;
    sc_in< sc_lv<32> > in_A_Dout_A;
    sc_out< sc_logic > in_A_Clk_A;
    sc_out< sc_logic > in_A_Rst_A;
    sc_out< sc_lv<32> > in_B_Addr_A;
    sc_out< sc_logic > in_B_EN_A;
    sc_out< sc_lv<4> > in_B_WEN_A;
    sc_out< sc_lv<32> > in_B_Din_A;
    sc_in< sc_lv<32> > in_B_Dout_A;
    sc_out< sc_logic > in_B_Clk_A;
    sc_out< sc_logic > in_B_Rst_A;
    sc_out< sc_lv<32> > out_C_Addr_A;
    sc_out< sc_logic > out_C_EN_A;
    sc_out< sc_lv<4> > out_C_WEN_A;
    sc_out< sc_lv<32> > out_C_Din_A;
    sc_in< sc_lv<32> > out_C_Dout_A;
    sc_out< sc_logic > out_C_Clk_A;
    sc_out< sc_logic > out_C_Rst_A;


    // Module declarations
    mmult_accel(sc_module_name name);
    SC_HAS_PROCESS(mmult_accel);

    ~mmult_accel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    mmult_accel_fadd_32ns_32ns_32_9_full_dsp<1,9,32,32,32>* mmult_accel_fadd_32ns_32ns_32_9_full_dsp_U1;
    mmult_accel_fmul_32ns_32ns_32_5_max_dsp<1,5,32,32,32>* mmult_accel_fmul_32ns_32ns_32_5_max_dsp_U2;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<19> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_37;
    sc_signal< sc_lv<6> > row_1_fu_148_p2;
    sc_signal< sc_lv<6> > row_1_reg_242;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_78;
    sc_signal< sc_lv<10> > tmp_fu_158_p3;
    sc_signal< sc_lv<10> > tmp_reg_247;
    sc_signal< sc_lv<1> > exitcond2_fu_142_p2;
    sc_signal< sc_lv<10> > col_cast2_fu_166_p1;
    sc_signal< sc_lv<10> > col_cast2_reg_253;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_93;
    sc_signal< sc_lv<6> > col_1_fu_176_p2;
    sc_signal< sc_lv<6> > col_1_reg_262;
    sc_signal< sc_lv<6> > k_1_fu_192_p2;
    sc_signal< sc_lv<6> > k_1_reg_270;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_104;
    sc_signal< sc_lv<1> > exitcond_fu_186_p2;
    sc_signal< sc_lv<32> > in_A_load_reg_285;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_119;
    sc_signal< sc_lv<32> > in_B_load_reg_290;
    sc_signal< sc_lv<32> > grp_fu_138_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_295;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_129;
    sc_signal< sc_lv<32> > grp_fu_133_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st19_fsm_18;
    sc_signal< bool > ap_sig_bdd_138;
    sc_signal< sc_lv<6> > row_reg_86;
    sc_signal< sc_lv<1> > exitcond1_fu_170_p2;
    sc_signal< sc_lv<6> > col_reg_97;
    sc_signal< sc_lv<32> > result_reg_108;
    sc_signal< sc_lv<6> > k_reg_121;
    sc_signal< sc_lv<64> > tmp_6_fu_203_p1;
    sc_signal< sc_lv<64> > tmp_9_fu_225_p1;
    sc_signal< sc_lv<64> > tmp_3_fu_234_p1;
    sc_signal< sc_lv<32> > in_A_Addr_A_orig;
    sc_signal< sc_lv<32> > in_B_Addr_A_orig;
    sc_signal< sc_lv<32> > out_C_Addr_A_orig;
    sc_signal< sc_lv<32> > grp_fu_133_p0;
    sc_signal< sc_lv<32> > grp_fu_133_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_bdd_179;
    sc_signal< sc_lv<32> > grp_fu_138_p0;
    sc_signal< sc_lv<32> > grp_fu_138_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_188;
    sc_signal< sc_lv<5> > tmp_1_fu_154_p1;
    sc_signal< sc_lv<10> > k_cast1_fu_182_p1;
    sc_signal< sc_lv<10> > tmp_5_fu_198_p2;
    sc_signal< sc_lv<5> > tmp_4_fu_208_p1;
    sc_signal< sc_lv<10> > tmp_7_fu_212_p3;
    sc_signal< sc_lv<10> > tmp_8_fu_220_p2;
    sc_signal< sc_lv<10> > tmp_2_fu_230_p2;
    sc_signal< sc_logic > grp_fu_133_ce;
    sc_signal< sc_logic > grp_fu_138_ce;
    sc_signal< sc_lv<19> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<19> ap_ST_st1_fsm_0;
    static const sc_lv<19> ap_ST_st2_fsm_1;
    static const sc_lv<19> ap_ST_st3_fsm_2;
    static const sc_lv<19> ap_ST_st4_fsm_3;
    static const sc_lv<19> ap_ST_st5_fsm_4;
    static const sc_lv<19> ap_ST_st6_fsm_5;
    static const sc_lv<19> ap_ST_st7_fsm_6;
    static const sc_lv<19> ap_ST_st8_fsm_7;
    static const sc_lv<19> ap_ST_st9_fsm_8;
    static const sc_lv<19> ap_ST_st10_fsm_9;
    static const sc_lv<19> ap_ST_st11_fsm_10;
    static const sc_lv<19> ap_ST_st12_fsm_11;
    static const sc_lv<19> ap_ST_st13_fsm_12;
    static const sc_lv<19> ap_ST_st14_fsm_13;
    static const sc_lv<19> ap_ST_st15_fsm_14;
    static const sc_lv<19> ap_ST_st16_fsm_15;
    static const sc_lv<19> ap_ST_st17_fsm_16;
    static const sc_lv<19> ap_ST_st18_fsm_17;
    static const sc_lv<19> ap_ST_st19_fsm_18;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<6> ap_const_lv6_20;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<5> ap_const_lv5_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_bdd_104();
    void thread_ap_sig_bdd_119();
    void thread_ap_sig_bdd_129();
    void thread_ap_sig_bdd_138();
    void thread_ap_sig_bdd_179();
    void thread_ap_sig_bdd_188();
    void thread_ap_sig_bdd_37();
    void thread_ap_sig_bdd_78();
    void thread_ap_sig_bdd_93();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st19_fsm_18();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_col_1_fu_176_p2();
    void thread_col_cast2_fu_166_p1();
    void thread_exitcond1_fu_170_p2();
    void thread_exitcond2_fu_142_p2();
    void thread_exitcond_fu_186_p2();
    void thread_grp_fu_133_ce();
    void thread_grp_fu_133_p0();
    void thread_grp_fu_133_p1();
    void thread_grp_fu_138_ce();
    void thread_grp_fu_138_p0();
    void thread_grp_fu_138_p1();
    void thread_in_A_Addr_A();
    void thread_in_A_Addr_A_orig();
    void thread_in_A_Clk_A();
    void thread_in_A_Din_A();
    void thread_in_A_EN_A();
    void thread_in_A_Rst_A();
    void thread_in_A_WEN_A();
    void thread_in_B_Addr_A();
    void thread_in_B_Addr_A_orig();
    void thread_in_B_Clk_A();
    void thread_in_B_Din_A();
    void thread_in_B_EN_A();
    void thread_in_B_Rst_A();
    void thread_in_B_WEN_A();
    void thread_k_1_fu_192_p2();
    void thread_k_cast1_fu_182_p1();
    void thread_out_C_Addr_A();
    void thread_out_C_Addr_A_orig();
    void thread_out_C_Clk_A();
    void thread_out_C_Din_A();
    void thread_out_C_EN_A();
    void thread_out_C_Rst_A();
    void thread_out_C_WEN_A();
    void thread_row_1_fu_148_p2();
    void thread_tmp_1_fu_154_p1();
    void thread_tmp_2_fu_230_p2();
    void thread_tmp_3_fu_234_p1();
    void thread_tmp_4_fu_208_p1();
    void thread_tmp_5_fu_198_p2();
    void thread_tmp_6_fu_203_p1();
    void thread_tmp_7_fu_212_p3();
    void thread_tmp_8_fu_220_p2();
    void thread_tmp_9_fu_225_p1();
    void thread_tmp_fu_158_p3();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
