#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" ::: 0
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 152 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 10 "<command line>" ::: 6
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 7
#pragma line 145 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 60
#pragma line 401 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 190
#pragma line 11 "<command line>" 2 ::: 193
#pragma line 1 "<built-in>" 2 ::: 194
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 195
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 1 3 ::: 196
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 206
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 217
#pragma line 18 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 223
#pragma line 62 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 237
#pragma line 10 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 244
#pragma line 32 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 248
#pragma line 147 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 251
#pragma line 225 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 255
#pragma line 247 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 257
#pragma line 277 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 259
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 260
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 274
#pragma line 674 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 280
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 281
#pragma line 674 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 282
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 284
#pragma line 675 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 285
#pragma line 13 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 286
#pragma line 46 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 306
#pragma line 99 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 308
#pragma line 277 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 313
#pragma line 316 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 317
#pragma line 370 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 323
#pragma line 380 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 325
#pragma line 392 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 327
#pragma line 405 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 329
#pragma line 418 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 331
#pragma line 436 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 333
#pragma line 456 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 336
#pragma line 518 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 356
#pragma line 605 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 370
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 434
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 1 3 4 ::: 436
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 1 3 4 ::: 475
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 482
#pragma line 6 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 2 3 4 ::: 488
#pragma line 38 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 2 3 4 ::: 503
#pragma line 60 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 509
#pragma line 90 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 511
#pragma line 102 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 513
#pragma line 10 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 518
#pragma line 36 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 525
#pragma line 46 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 527
#pragma line 100 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 572
#pragma line 132 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 582
#pragma line 172 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 609
#pragma line 200 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 627
#pragma line 209 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 629
#pragma line 218 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 631
#pragma line 227 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 633
#pragma line 257 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 656
#pragma line 266 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 658
#pragma line 275 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 660
#pragma line 284 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 662
#pragma line 321 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 692
#pragma line 574 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 926
#pragma line 624 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 964
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdlib_s.h" 1 3 ::: 971
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 1 3 ::: 981
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdlib_s.h" 2 3 ::: 987
#pragma line 629 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 988
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 1 3 ::: 990
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 1000
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 2 3 ::: 1006
#pragma line 31 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1017
#pragma line 98 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1043
#pragma line 140 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1074
#pragma line 159 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1082
#pragma line 202 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1098
#pragma line 630 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 1103
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 1104
#pragma line 1 "C:/labs/lab1_prebuilt/src\\madd.h" 1 ::: 1106
#pragma line 2 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 1114
