#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" ::: -10
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 152 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 10 "<command line>" ::: -4
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: -3
#pragma line 145 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 50
#pragma line 401 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 180
#pragma line 11 "<command line>" 2 ::: 183
#pragma line 1 "<built-in>" 2 ::: 184
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 185
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 1 3 ::: 186
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 196
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 1 3 ::: 207
#pragma line 18 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 213
#pragma line 62 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/_mingw_mac.h" 3 ::: 227
#pragma line 10 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 234
#pragma line 32 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 238
#pragma line 147 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 241
#pragma line 225 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 245
#pragma line 247 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 247
#pragma line 277 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 249
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 1 3 ::: 250
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 264
#pragma line 674 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 270
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_directx.h" 1 3 ::: 271
#pragma line 674 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 272
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include/sdks/_mingw_ddk.h" 1 3 ::: 274
#pragma line 675 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 275
#pragma line 13 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 2 3 ::: 276
#pragma line 46 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 296
#pragma line 99 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\vadefs.h" 3 ::: 298
#pragma line 277 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 2 3 ::: 303
#pragma line 316 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 307
#pragma line 370 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 313
#pragma line 380 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 315
#pragma line 392 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 317
#pragma line 405 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 319
#pragma line 418 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 321
#pragma line 436 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 323
#pragma line 456 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 326
#pragma line 518 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 346
#pragma line 605 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 3 ::: 360
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 424
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 1 3 4 ::: 426
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 1 3 4 ::: 465
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 4 ::: 472
#pragma line 6 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\limits.h" 2 3 4 ::: 478
#pragma line 38 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 2 3 4 ::: 493
#pragma line 60 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 499
#pragma line 90 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 501
#pragma line 102 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/include\\limits.h" 3 4 ::: 503
#pragma line 10 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 508
#pragma line 36 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 515
#pragma line 46 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 517
#pragma line 100 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 562
#pragma line 132 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 572
#pragma line 172 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 599
#pragma line 200 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 617
#pragma line 209 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 619
#pragma line 218 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 621
#pragma line 227 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 623
#pragma line 257 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 646
#pragma line 266 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 648
#pragma line 275 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 650
#pragma line 284 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 652
#pragma line 321 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 682
#pragma line 574 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 916
#pragma line 624 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 3 ::: 954
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdlib_s.h" 1 3 ::: 961
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 1 3 ::: 971
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\sec_api/stdlib_s.h" 2 3 ::: 977
#pragma line 629 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 978
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 1 3 ::: 980
#pragma line 1 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\_mingw.h" 1 3 ::: 990
#pragma line 9 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 2 3 ::: 996
#pragma line 31 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1007
#pragma line 98 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1033
#pragma line 140 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1064
#pragma line 159 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1072
#pragma line 202 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\malloc.h" 3 ::: 1088
#pragma line 630 "C:/Xilinx/SDSoC/2014.4/VIVADO~1/2014.4/win64/tools/clang/bin/../lib/clang/3.1/../../../x86_64-w64-mingw32/include\\stdlib.h" 2 3 ::: 1093
#pragma line 1 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 1094
#pragma line 1 "C:/labs/lab1_prebuilt/src\\madd.h" 1 ::: 1096
#pragma line 2 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" 2 ::: 1104
#pragma line 20 "C:/labs/lab1_prebuilt/SDRelease/_sds/vhls/src/madd.cpp" ::: 1124
