#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" ::: -10
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 4
#pragma line 145 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 401 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 10 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 2 ::: 192
#pragma line 1 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 1 ::: 214
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/hls_stream.h" 1 ::: 242
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 309
#pragma line 67 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/common/technology/autopilot/hls_stream.h" 2 ::: 438
#pragma line 28 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 2 ::: 533
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 535
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 564
#pragma line 122 "/usr/include/features.h" 3 4 ::: 660
#pragma line 146 "/usr/include/features.h" 3 4 ::: 677
#pragma line 177 "/usr/include/features.h" 3 4 ::: 686
#pragma line 326 "/usr/include/features.h" 3 4 ::: 713
#pragma line 1 "/usr/include/sys/cdefs.h" 1 3 4 ::: 750
#pragma line 72 "/usr/include/sys/cdefs.h" 3 4 ::: 796
#pragma line 98 "/usr/include/sys/cdefs.h" 3 4 ::: 814
#pragma line 111 "/usr/include/sys/cdefs.h" 3 4 ::: 820
#pragma line 123 "/usr/include/sys/cdefs.h" 3 4 ::: 824
#pragma line 150 "/usr/include/sys/cdefs.h" 3 4 ::: 834
#pragma line 168 "/usr/include/sys/cdefs.h" 3 4 ::: 838
#pragma line 191 "/usr/include/sys/cdefs.h" 3 4 ::: 848
#pragma line 235 "/usr/include/sys/cdefs.h" 3 4 ::: 885
#pragma line 288 "/usr/include/sys/cdefs.h" 3 4 ::: 926
#pragma line 324 "/usr/include/sys/cdefs.h" 3 4 ::: 936
#pragma line 334 "/usr/include/sys/cdefs.h" 3 4 ::: 939
#pragma line 373 "/usr/include/sys/cdefs.h" 3 4 ::: 956
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 957
#pragma line 374 "/usr/include/sys/cdefs.h" 2 3 4 ::: 959
#pragma line 362 "/usr/include/features.h" 2 3 4 ::: 960
#pragma line 1 "/usr/include/gnu/stubs.h" 1 3 4 ::: 985
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 990
#pragma line 5 "/usr/include/gnu/stubs.h" 2 3 4 ::: 992
#pragma line 1 "/usr/include/gnu/stubs-64.h" 1 3 4 ::: 997
#pragma line 10 "/usr/include/gnu/stubs.h" 2 3 4 ::: 1002
#pragma line 386 "/usr/include/features.h" 2 3 4 ::: 1003
#pragma line 29 "/usr/include/math.h" 2 3 4 ::: 1004
#pragma line 1 "/usr/include/bits/huge_val.h" 1 3 4 ::: 1011
#pragma line 35 "/usr/include/math.h" 2 3 4 ::: 1038
#pragma line 1 "/usr/include/bits/huge_valf.h" 1 3 4 ::: 1040
#pragma line 37 "/usr/include/math.h" 2 3 4 ::: 1067
#pragma line 1 "/usr/include/bits/huge_vall.h" 1 3 4 ::: 1068
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1088
#pragma line 1 "/usr/include/bits/inf.h" 1 3 4 ::: 1092
#pragma line 41 "/usr/include/math.h" 2 3 4 ::: 1117
#pragma line 1 "/usr/include/bits/nan.h" 1 3 4 ::: 1121
#pragma line 44 "/usr/include/math.h" 2 3 4 ::: 1147
#pragma line 1 "/usr/include/bits/mathdef.h" 1 3 4 ::: 1152
#pragma line 26 "/usr/include/bits/mathdef.h" 3 4 ::: 1170
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 1171
#pragma line 27 "/usr/include/bits/mathdef.h" 2 3 4 ::: 1173
#pragma line 44 "/usr/include/bits/mathdef.h" 3 4 ::: 1181
#pragma line 48 "/usr/include/math.h" 2 3 4 ::: 1183
#pragma line 71 "/usr/include/math.h" 3 4 ::: 1189
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1190
#pragma line 72 "/usr/include/math.h" 2 3 4 ::: 1555
#pragma line 94 "/usr/include/math.h" 3 4 ::: 1566
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1567
#pragma line 95 "/usr/include/math.h" 2 3 4 ::: 1932
#pragma line 141 "/usr/include/math.h" 3 4 ::: 1933
#pragma line 1 "/usr/include/bits/mathcalls.h" 1 3 4 ::: 1934
#pragma line 142 "/usr/include/math.h" 2 3 4 ::: 2299
#pragma line 156 "/usr/include/math.h" 3 4 ::: 2300
#pragma line 224 "/usr/include/math.h" 3 4 ::: 2358
#pragma line 236 "/usr/include/math.h" 3 4 ::: 2360
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2362
#pragma line 264 "/usr/include/math.h" 3 4 ::: 2368
#pragma line 276 "/usr/include/math.h" 3 4 ::: 2370
#pragma line 355 "/usr/include/math.h" 3 4 ::: 2438
#pragma line 372 "/usr/include/math.h" 3 4 ::: 2440
#pragma line 392 "/usr/include/math.h" 3 4 ::: 2444
#pragma line 414 "/usr/include/math.h" 3 4 ::: 2459
#pragma line 472 "/usr/include/math.h" 3 4 ::: 2509
#pragma line 29 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 2 ::: 2511
#pragma line 29 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" ::: 2513
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 2525
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2560
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2596
#pragma line 35 "/usr/include/string.h" 2 3 4 ::: 2599
#pragma line 95 "/usr/include/string.h" 3 4 ::: 2637
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2706
#pragma line 40 "/usr/include/xlocale.h" ::: 2749
#pragma line 163 "/usr/include/string.h" 2 3 4 ::: 2754
#pragma line 198 "/usr/include/string.h" 3 4 ::: 2781
#pragma line 211 "/usr/include/string.h" 3 4 ::: 2783
#pragma line 235 "/usr/include/string.h" 3 4 ::: 2785
#pragma line 262 "/usr/include/string.h" 3 4 ::: 2790
#pragma line 314 "/usr/include/string.h" 3 4 ::: 2820
#pragma line 342 "/usr/include/string.h" 3 4 ::: 2825
#pragma line 436 "/usr/include/string.h" 3 4 ::: 2907
#pragma line 489 "/usr/include/string.h" 3 4 ::: 2938
#pragma line 517 "/usr/include/string.h" 3 4 ::: 2944
#pragma line 646 "/usr/include/string.h" 3 4 ::: 3035
#pragma line 39 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 2 ::: 3037
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 3038
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3072
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3097
#pragma line 34 "/usr/include/stdlib.h" 2 3 4 ::: 3100
#pragma line 1 "/usr/include/bits/waitflags.h" 1 3 4 ::: 3110
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 3140
#pragma line 1 "/usr/include/bits/waitstatus.h" 1 3 4 ::: 3141
#pragma line 65 "/usr/include/bits/waitstatus.h" 3 4 ::: 3198
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 3199
#pragma line 1 "/usr/include/bits/endian.h" 1 3 4 ::: 3237
#pragma line 38 "/usr/include/endian.h" 2 3 4 ::: 3239
#pragma line 60 "/usr/include/endian.h" 3 4 ::: 3243
#pragma line 1 "/usr/include/bits/byteswap.h" 1 3 4 ::: 3246
#pragma line 28 "/usr/include/bits/byteswap.h" 3 4 ::: 3266
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3267
#pragma line 29 "/usr/include/bits/byteswap.h" 2 3 4 ::: 3269
#pragma line 55 "/usr/include/bits/byteswap.h" 3 4 ::: 3272
#pragma line 67 "/usr/include/bits/byteswap.h" 3 4 ::: 3274
#pragma line 100 "/usr/include/bits/byteswap.h" 3 4 ::: 3277
#pragma line 62 "/usr/include/endian.h" 2 3 4 ::: 3279
#pragma line 66 "/usr/include/bits/waitstatus.h" 2 3 4 ::: 3280
#pragma line 44 "/usr/include/stdlib.h" 2 3 4 ::: 3314
#pragma line 58 "/usr/include/stdlib.h" 3 4 ::: 3320
#pragma line 84 "/usr/include/stdlib.h" 3 4 ::: 3325
#pragma line 97 "/usr/include/stdlib.h" 3 4 ::: 3327
#pragma line 308 "/usr/include/stdlib.h" 3 4 ::: 3504
#pragma line 1 "/usr/include/sys/types.h" 1 3 4 ::: 3518
#pragma line 1 "/usr/include/bits/types.h" 1 3 4 ::: 3549
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 3578
#pragma line 29 "/usr/include/bits/types.h" 2 3 4 ::: 3580
#pragma line 70 "/usr/include/bits/types.h" 3 4 ::: 3607
#pragma line 126 "/usr/include/bits/types.h" 3 4 ::: 3636
#pragma line 1 "/usr/include/bits/typesizes.h" 1 3 4 ::: 3643
#pragma line 27 "/usr/include/bits/typesizes.h" 3 4 ::: 3662
#pragma line 62 "/usr/include/bits/typesizes.h" 3 4 ::: 3665
#pragma line 132 "/usr/include/bits/types.h" 2 3 4 ::: 3667
#pragma line 31 "/usr/include/sys/types.h" 2 3 4 ::: 3729
#pragma line 133 "/usr/include/sys/types.h" 3 4 ::: 3823
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3824
#pragma line 59 "/usr/include/time.h" 3 4 ::: 3846
#pragma line 75 "/usr/include/time.h" 3 4 ::: 3849
#pragma line 91 "/usr/include/time.h" 3 4 ::: 3852
#pragma line 103 "/usr/include/time.h" 3 4 ::: 3855
#pragma line 134 "/usr/include/sys/types.h" 2 3 4 ::: 3858
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3873
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3898
#pragma line 148 "/usr/include/sys/types.h" 2 3 4 ::: 3901
#pragma line 187 "/usr/include/sys/types.h" 3 4 ::: 3911
#pragma line 1 "/usr/include/sys/select.h" 1 3 4 ::: 3946
#pragma line 1 "/usr/include/bits/select.h" 1 3 4 ::: 3978
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4002
#pragma line 24 "/usr/include/bits/select.h" 2 3 4 ::: 4004
#pragma line 32 "/usr/include/sys/select.h" 2 3 4 ::: 4005
#pragma line 1 "/usr/include/bits/sigset.h" 1 3 4 ::: 4009
#pragma line 35 "/usr/include/sys/select.h" 2 3 4 ::: 4051
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 4062
#pragma line 118 "/usr/include/time.h" 3 4 ::: 4084
#pragma line 45 "/usr/include/sys/select.h" 2 3 4 ::: 4092
#pragma line 1 "/usr/include/bits/time.h" 1 3 4 ::: 4094
#pragma line 73 "/usr/include/bits/time.h" 3 4 ::: 4117
#pragma line 47 "/usr/include/sys/select.h" 2 3 4 ::: 4125
#pragma line 221 "/usr/include/sys/types.h" 2 3 4 ::: 4208
#pragma line 1 "/usr/include/sys/sysmacros.h" 1 3 4 ::: 4212
#pragma line 64 "/usr/include/sys/sysmacros.h" 3 4 ::: 4252
#pragma line 224 "/usr/include/sys/types.h" 2 3 4 ::: 4254
#pragma line 263 "/usr/include/sys/types.h" 3 4 ::: 4276
#pragma line 1 "/usr/include/bits/pthreadtypes.h" 1 3 4 ::: 4286
#pragma line 1 "/usr/include/bits/wordsize.h" 1 3 4 ::: 4310
#pragma line 24 "/usr/include/bits/pthreadtypes.h" 2 3 4 ::: 4312
#pragma line 48 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4313
#pragma line 74 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4332
#pragma line 101 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4351
#pragma line 187 "/usr/include/bits/pthreadtypes.h" 3 4 ::: 4420
#pragma line 272 "/usr/include/sys/types.h" 2 3 4 ::: 4451
#pragma line 321 "/usr/include/stdlib.h" 2 3 4 ::: 4455
#pragma line 470 "/usr/include/stdlib.h" 3 4 ::: 4597
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 4626
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 4652
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 4677
#pragma line 26 "/usr/include/alloca.h" 2 3 4 ::: 4680
#pragma line 498 "/usr/include/stdlib.h" 2 3 4 ::: 4695
#pragma line 630 "/usr/include/stdlib.h" 3 4 ::: 4819
#pragma line 652 "/usr/include/stdlib.h" 3 4 ::: 4833
#pragma line 684 "/usr/include/stdlib.h" 3 4 ::: 4857
#pragma line 706 "/usr/include/stdlib.h" 3 4 ::: 4870
#pragma line 964 "/usr/include/stdlib.h" 3 4 ::: 5119
#pragma line 40 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 2 ::: 5121
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 5122
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5157
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5182
#pragma line 35 "/usr/include/stdio.h" 2 3 4 ::: 5185
#pragma line 44 "/usr/include/stdio.h" 3 4 ::: 5186
#pragma line 64 "/usr/include/stdio.h" 3 4 ::: 5193
#pragma line 75 "/usr/include/stdio.h" 3 4 ::: 5196
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 5197
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 5230
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 5246
#pragma line 56 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 5271
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 5274
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 5279
#pragma line 82 "/usr/include/wchar.h" 3 4 ::: 5302
#pragma line 895 "/usr/include/wchar.h" 3 4 ::: 5323
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 5326
#pragma line 53 "/usr/include/_G_config.h" 3 4 ::: 5338
#pragma line 82 "/usr/include/_G_config.h" 3 4 ::: 5348
#pragma line 33 "/usr/include/libio.h" 2 3 4 ::: 5355
#pragma line 51 "/usr/include/libio.h" 3 4 ::: 5357
#pragma line 1 "/opt/Xilinx/SDSoC/2014.4/Vivado_HLS/2014.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 5361
#pragma line 54 "/usr/include/libio.h" 2 3 4 ::: 5410
#pragma line 74 "/usr/include/libio.h" 3 4 ::: 5411
#pragma line 114 "/usr/include/libio.h" 3 4 ::: 5413
#pragma line 150 "/usr/include/libio.h" 3 4 ::: 5419
#pragma line 170 "/usr/include/libio.h" 3 4 ::: 5421
#pragma line 203 "/usr/include/libio.h" 3 4 ::: 5445
#pragma line 271 "/usr/include/libio.h" 3 4 ::: 5456
#pragma line 319 "/usr/include/libio.h" 3 4 ::: 5497
#pragma line 328 "/usr/include/libio.h" 3 4 ::: 5499
#pragma line 360 "/usr/include/libio.h" 3 4 ::: 5521
#pragma line 460 "/usr/include/libio.h" 3 4 ::: 5581
#pragma line 490 "/usr/include/libio.h" 3 4 ::: 5596
#pragma line 552 "/usr/include/libio.h" 3 4 ::: 5608
#pragma line 76 "/usr/include/stdio.h" 2 3 4 ::: 5610
#pragma line 108 "/usr/include/stdio.h" 3 4 ::: 5616
#pragma line 1 "/usr/include/bits/stdio_lim.h" 1 3 4 ::: 5671
#pragma line 162 "/usr/include/stdio.h" 2 3 4 ::: 5689
#pragma line 204 "/usr/include/stdio.h" 3 4 ::: 5723
#pragma line 296 "/usr/include/stdio.h" 3 4 ::: 5800
#pragma line 471 "/usr/include/stdio.h" 3 4 ::: 5944
#pragma line 531 "/usr/include/stdio.h" 3 4 ::: 5964
#pragma line 789 "/usr/include/stdio.h" 3 4 ::: 6208
#pragma line 813 "/usr/include/stdio.h" 3 4 ::: 6219
#pragma line 1 "/usr/include/bits/sys_errlist.h" 1 3 4 ::: 6256
#pragma line 849 "/usr/include/stdio.h" 2 3 4 ::: 6289
#pragma line 926 "/usr/include/stdio.h" 3 4 ::: 6357
#pragma line 938 "/usr/include/stdio.h" 3 4 ::: 6360
#pragma line 41 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" 2 ::: 6362
#pragma line 54 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/src/correlation_accel_v1.hpp" ::: 6366
#pragma line 22 "/home/trungnguyen/SDSoC/workspace/correlation_ver1/correlation_ver1_linux/SDRelease/_sds/vhls/src/correlation_accel_v1.cpp" 2 ::: 6391
