-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity correlation_accel_v3 is
port (
    number_of_days : IN STD_LOGIC_VECTOR (31 downto 0);
    number_of_indices : IN STD_LOGIC_VECTOR (31 downto 0);
    in_indices_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_indices_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_indices_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_indices_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_indices_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_indices_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_indices_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_correlation_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_correlation_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_correlation_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_correlation_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_correlation_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_correlation_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_correlation_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_indices_TVALID : IN STD_LOGIC;
    in_indices_TREADY : OUT STD_LOGIC;
    out_correlation_TVALID : OUT STD_LOGIC;
    out_correlation_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of correlation_accel_v3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "correlation_accel_v3,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=8.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.646000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=19,HLS_SYN_DSP=80,HLS_SYN_FF=17826,HLS_SYN_LUT=25028}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_true : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_ap_start : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_ap_done : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_ap_continue : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_ap_idle : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_ap_ready : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TVALID : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_in_indices_TREADY : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_in_indices_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_frontEnd_U0_in_indices_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_return_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_return_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_return_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_write : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_din : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_full_n : STD_LOGIC;
    signal correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_write : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_ap_start : STD_LOGIC := '0';
    signal correlation_accel_v3_backEnd_U0_ap_done : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_ap_continue : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_ap_idle : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_ap_ready : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_return_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_return_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_return_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_returnA_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_returnA_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_returnA_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_empty_n : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_read : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_out_correlation_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TVALID : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_out_correlation_TREADY : STD_LOGIC;
    signal correlation_accel_v3_backEnd_U0_out_correlation_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal correlation_accel_v3_backEnd_U0_out_correlation_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_hs_continue : STD_LOGIC;
    signal sum_weight_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_V_full_n : STD_LOGIC;
    signal sum_weight_V_write : STD_LOGIC;
    signal sum_weight_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_V_empty_n : STD_LOGIC;
    signal sum_weight_V_read : STD_LOGIC;
    signal sum_return_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_return_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_return_V_full_n : STD_LOGIC;
    signal sum_return_V_write : STD_LOGIC;
    signal sum_return_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_return_V_empty_n : STD_LOGIC;
    signal sum_return_V_read : STD_LOGIC;
    signal sum_weight_returnSquare_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_returnSquare_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnSquare_V_full_n : STD_LOGIC;
    signal sum_weight_returnSquare_V_write : STD_LOGIC;
    signal sum_weight_returnSquare_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnSquare_V_empty_n : STD_LOGIC;
    signal sum_weight_returnSquare_V_read : STD_LOGIC;
    signal sum_weight_return_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_return_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_return_V_full_n : STD_LOGIC;
    signal sum_weight_return_V_write : STD_LOGIC;
    signal sum_weight_return_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_return_V_empty_n : STD_LOGIC;
    signal sum_weight_return_V_read : STD_LOGIC;
    signal sum_weight_returnA_returnB_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_returnA_returnB_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnA_returnB_V_full_n : STD_LOGIC;
    signal sum_weight_returnA_returnB_V_write : STD_LOGIC;
    signal sum_weight_returnA_returnB_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnA_returnB_V_empty_n : STD_LOGIC;
    signal sum_weight_returnA_returnB_V_read : STD_LOGIC;
    signal sum_returnA_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_returnA_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_returnA_V_full_n : STD_LOGIC;
    signal sum_returnA_V_write : STD_LOGIC;
    signal sum_returnA_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_returnA_V_empty_n : STD_LOGIC;
    signal sum_returnA_V_read : STD_LOGIC;
    signal sum_weight_returnSquareA_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_returnSquareA_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnSquareA_V_full_n : STD_LOGIC;
    signal sum_weight_returnSquareA_V_write : STD_LOGIC;
    signal sum_weight_returnSquareA_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnSquareA_V_empty_n : STD_LOGIC;
    signal sum_weight_returnSquareA_V_read : STD_LOGIC;
    signal sum_weight_returnA_V_U_ap_dummy_ce : STD_LOGIC;
    signal sum_weight_returnA_V_din : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnA_V_full_n : STD_LOGIC;
    signal sum_weight_returnA_V_write : STD_LOGIC;
    signal sum_weight_returnA_V_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_weight_returnA_V_empty_n : STD_LOGIC;
    signal sum_weight_returnA_V_read : STD_LOGIC;
    signal number_of_days14_channel_U_ap_dummy_ce : STD_LOGIC;
    signal number_of_days14_channel_din : STD_LOGIC_VECTOR (31 downto 0);
    signal number_of_days14_channel_full_n : STD_LOGIC;
    signal number_of_days14_channel_write : STD_LOGIC;
    signal number_of_days14_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal number_of_days14_channel_empty_n : STD_LOGIC;
    signal number_of_days14_channel_read : STD_LOGIC;
    signal number_of_indices15_channel_U_ap_dummy_ce : STD_LOGIC;
    signal number_of_indices15_channel_din : STD_LOGIC_VECTOR (31 downto 0);
    signal number_of_indices15_channel_full_n : STD_LOGIC;
    signal number_of_indices15_channel_write : STD_LOGIC;
    signal number_of_indices15_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal number_of_indices15_channel_empty_n : STD_LOGIC;
    signal number_of_indices15_channel_read : STD_LOGIC;
    signal ap_reg_procdone_correlation_accel_v3_frontEnd_U0 : STD_LOGIC := '0';
    signal ap_sig_hs_done : STD_LOGIC;
    signal ap_reg_procdone_correlation_accel_v3_backEnd_U0 : STD_LOGIC := '0';
    signal ap_CS : STD_LOGIC;
    signal ap_sig_top_allready : STD_LOGIC;

    component correlation_accel_v3_frontEnd IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        NUMBER_OF_DAYS : IN STD_LOGIC_VECTOR (31 downto 0);
        NUMBER_OF_INDICES : IN STD_LOGIC_VECTOR (31 downto 0);
        in_indices_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_indices_TVALID : IN STD_LOGIC;
        in_indices_TREADY : OUT STD_LOGIC;
        in_indices_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_indices_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_indices_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_indices_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_indices_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_indices_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        sum_weight_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_out_V_full_n : IN STD_LOGIC;
        sum_weight_out_V_write : OUT STD_LOGIC;
        sum_return_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_return_out_V_full_n : IN STD_LOGIC;
        sum_return_out_V_write : OUT STD_LOGIC;
        sum_weight_returnSquare_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnSquare_out_V_full_n : IN STD_LOGIC;
        sum_weight_returnSquare_out_V_write : OUT STD_LOGIC;
        sum_weight_return_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_return_out_V_full_n : IN STD_LOGIC;
        sum_weight_return_out_V_write : OUT STD_LOGIC;
        sum_weight_returnA_returnB_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnA_returnB_out_full_n : IN STD_LOGIC;
        sum_weight_returnA_returnB_out_write : OUT STD_LOGIC;
        sum_returnA_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_returnA_out_V_full_n : IN STD_LOGIC;
        sum_returnA_out_V_write : OUT STD_LOGIC;
        sum_weight_returnSquareA_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnSquareA_out_V_full_n : IN STD_LOGIC;
        sum_weight_returnSquareA_out_V_write : OUT STD_LOGIC;
        sum_weight_returnA_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnA_out_V_full_n : IN STD_LOGIC;
        sum_weight_returnA_out_V_write : OUT STD_LOGIC;
        NUMBER_OF_DAYS_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        NUMBER_OF_DAYS_out_full_n : IN STD_LOGIC;
        NUMBER_OF_DAYS_out_write : OUT STD_LOGIC;
        NUMBER_OF_INDICES_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        NUMBER_OF_INDICES_out_full_n : IN STD_LOGIC;
        NUMBER_OF_INDICES_out_write : OUT STD_LOGIC );
    end component;


    component correlation_accel_v3_backEnd IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        NUMBER_OF_DAYS_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        NUMBER_OF_DAYS_empty_n : IN STD_LOGIC;
        NUMBER_OF_DAYS_read : OUT STD_LOGIC;
        NUMBER_OF_INDICES_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        NUMBER_OF_INDICES_empty_n : IN STD_LOGIC;
        NUMBER_OF_INDICES_read : OUT STD_LOGIC;
        sum_weight_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_in_V_empty_n : IN STD_LOGIC;
        sum_weight_in_V_read : OUT STD_LOGIC;
        sum_return_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_return_in_V_empty_n : IN STD_LOGIC;
        sum_return_in_V_read : OUT STD_LOGIC;
        sum_weight_returnSquare_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnSquare_in_V_empty_n : IN STD_LOGIC;
        sum_weight_returnSquare_in_V_read : OUT STD_LOGIC;
        sum_weight_return_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_return_in_V_empty_n : IN STD_LOGIC;
        sum_weight_return_in_V_read : OUT STD_LOGIC;
        sum_weight_returnA_returnB_in_s_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnA_returnB_in_s_empty_n : IN STD_LOGIC;
        sum_weight_returnA_returnB_in_s_read : OUT STD_LOGIC;
        sum_returnA_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_returnA_in_V_empty_n : IN STD_LOGIC;
        sum_returnA_in_V_read : OUT STD_LOGIC;
        sum_weight_returnSquareA_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnSquareA_in_V_empty_n : IN STD_LOGIC;
        sum_weight_returnSquareA_in_V_read : OUT STD_LOGIC;
        sum_weight_returnA_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        sum_weight_returnA_in_V_empty_n : IN STD_LOGIC;
        sum_weight_returnA_in_V_read : OUT STD_LOGIC;
        out_correlation_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_correlation_TVALID : OUT STD_LOGIC;
        out_correlation_TREADY : IN STD_LOGIC;
        out_correlation_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_correlation_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_correlation_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_correlation_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_correlation_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_correlation_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_return_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_returnSquare_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_return_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_returnA_returnB_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_returnA_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_returnSquareA_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_sum_weight_returnA_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_number_of_days14_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_correlation_accel_v3_number_of_indices15_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    correlation_accel_v3_frontEnd_U0 : component correlation_accel_v3_frontEnd
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => correlation_accel_v3_frontEnd_U0_ap_start,
        ap_done => correlation_accel_v3_frontEnd_U0_ap_done,
        ap_continue => correlation_accel_v3_frontEnd_U0_ap_continue,
        ap_idle => correlation_accel_v3_frontEnd_U0_ap_idle,
        ap_ready => correlation_accel_v3_frontEnd_U0_ap_ready,
        NUMBER_OF_DAYS => correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS,
        NUMBER_OF_INDICES => correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES,
        in_indices_TDATA => correlation_accel_v3_frontEnd_U0_in_indices_TDATA,
        in_indices_TVALID => correlation_accel_v3_frontEnd_U0_in_indices_TVALID,
        in_indices_TREADY => correlation_accel_v3_frontEnd_U0_in_indices_TREADY,
        in_indices_TKEEP => correlation_accel_v3_frontEnd_U0_in_indices_TKEEP,
        in_indices_TSTRB => correlation_accel_v3_frontEnd_U0_in_indices_TSTRB,
        in_indices_TUSER => correlation_accel_v3_frontEnd_U0_in_indices_TUSER,
        in_indices_TLAST => correlation_accel_v3_frontEnd_U0_in_indices_TLAST,
        in_indices_TID => correlation_accel_v3_frontEnd_U0_in_indices_TID,
        in_indices_TDEST => correlation_accel_v3_frontEnd_U0_in_indices_TDEST,
        sum_weight_out_V_din => correlation_accel_v3_frontEnd_U0_sum_weight_out_V_din,
        sum_weight_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_out_V_full_n,
        sum_weight_out_V_write => correlation_accel_v3_frontEnd_U0_sum_weight_out_V_write,
        sum_return_out_V_din => correlation_accel_v3_frontEnd_U0_sum_return_out_V_din,
        sum_return_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_return_out_V_full_n,
        sum_return_out_V_write => correlation_accel_v3_frontEnd_U0_sum_return_out_V_write,
        sum_weight_returnSquare_out_V_din => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_din,
        sum_weight_returnSquare_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_full_n,
        sum_weight_returnSquare_out_V_write => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_write,
        sum_weight_return_out_V_din => correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_din,
        sum_weight_return_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_full_n,
        sum_weight_return_out_V_write => correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_write,
        sum_weight_returnA_returnB_out_din => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_din,
        sum_weight_returnA_returnB_out_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_full_n,
        sum_weight_returnA_returnB_out_write => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_write,
        sum_returnA_out_V_din => correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_din,
        sum_returnA_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_full_n,
        sum_returnA_out_V_write => correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_write,
        sum_weight_returnSquareA_out_V_din => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_din,
        sum_weight_returnSquareA_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_full_n,
        sum_weight_returnSquareA_out_V_write => correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_write,
        sum_weight_returnA_out_V_din => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_din,
        sum_weight_returnA_out_V_full_n => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_full_n,
        sum_weight_returnA_out_V_write => correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_write,
        NUMBER_OF_DAYS_out_din => correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_din,
        NUMBER_OF_DAYS_out_full_n => correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_full_n,
        NUMBER_OF_DAYS_out_write => correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_write,
        NUMBER_OF_INDICES_out_din => correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_din,
        NUMBER_OF_INDICES_out_full_n => correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_full_n,
        NUMBER_OF_INDICES_out_write => correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_write);

    correlation_accel_v3_backEnd_U0 : component correlation_accel_v3_backEnd
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => correlation_accel_v3_backEnd_U0_ap_start,
        ap_done => correlation_accel_v3_backEnd_U0_ap_done,
        ap_continue => correlation_accel_v3_backEnd_U0_ap_continue,
        ap_idle => correlation_accel_v3_backEnd_U0_ap_idle,
        ap_ready => correlation_accel_v3_backEnd_U0_ap_ready,
        NUMBER_OF_DAYS_dout => correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_dout,
        NUMBER_OF_DAYS_empty_n => correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_empty_n,
        NUMBER_OF_DAYS_read => correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_read,
        NUMBER_OF_INDICES_dout => correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_dout,
        NUMBER_OF_INDICES_empty_n => correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_empty_n,
        NUMBER_OF_INDICES_read => correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_read,
        sum_weight_in_V_dout => correlation_accel_v3_backEnd_U0_sum_weight_in_V_dout,
        sum_weight_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_in_V_empty_n,
        sum_weight_in_V_read => correlation_accel_v3_backEnd_U0_sum_weight_in_V_read,
        sum_return_in_V_dout => correlation_accel_v3_backEnd_U0_sum_return_in_V_dout,
        sum_return_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_return_in_V_empty_n,
        sum_return_in_V_read => correlation_accel_v3_backEnd_U0_sum_return_in_V_read,
        sum_weight_returnSquare_in_V_dout => correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_dout,
        sum_weight_returnSquare_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_empty_n,
        sum_weight_returnSquare_in_V_read => correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_read,
        sum_weight_return_in_V_dout => correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_dout,
        sum_weight_return_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_empty_n,
        sum_weight_return_in_V_read => correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_read,
        sum_weight_returnA_returnB_in_s_dout => correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_dout,
        sum_weight_returnA_returnB_in_s_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_empty_n,
        sum_weight_returnA_returnB_in_s_read => correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_read,
        sum_returnA_in_V_dout => correlation_accel_v3_backEnd_U0_sum_returnA_in_V_dout,
        sum_returnA_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_returnA_in_V_empty_n,
        sum_returnA_in_V_read => correlation_accel_v3_backEnd_U0_sum_returnA_in_V_read,
        sum_weight_returnSquareA_in_V_dout => correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_dout,
        sum_weight_returnSquareA_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_empty_n,
        sum_weight_returnSquareA_in_V_read => correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_read,
        sum_weight_returnA_in_V_dout => correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_dout,
        sum_weight_returnA_in_V_empty_n => correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_empty_n,
        sum_weight_returnA_in_V_read => correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_read,
        out_correlation_TDATA => correlation_accel_v3_backEnd_U0_out_correlation_TDATA,
        out_correlation_TVALID => correlation_accel_v3_backEnd_U0_out_correlation_TVALID,
        out_correlation_TREADY => correlation_accel_v3_backEnd_U0_out_correlation_TREADY,
        out_correlation_TKEEP => correlation_accel_v3_backEnd_U0_out_correlation_TKEEP,
        out_correlation_TSTRB => correlation_accel_v3_backEnd_U0_out_correlation_TSTRB,
        out_correlation_TUSER => correlation_accel_v3_backEnd_U0_out_correlation_TUSER,
        out_correlation_TLAST => correlation_accel_v3_backEnd_U0_out_correlation_TLAST,
        out_correlation_TID => correlation_accel_v3_backEnd_U0_out_correlation_TID,
        out_correlation_TDEST => correlation_accel_v3_backEnd_U0_out_correlation_TDEST);

    sum_weight_V_U : component FIFO_correlation_accel_v3_sum_weight_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_V_U_ap_dummy_ce,
        if_din => sum_weight_V_din,
        if_full_n => sum_weight_V_full_n,
        if_write => sum_weight_V_write,
        if_dout => sum_weight_V_dout,
        if_empty_n => sum_weight_V_empty_n,
        if_read => sum_weight_V_read);

    sum_return_V_U : component FIFO_correlation_accel_v3_sum_return_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_return_V_U_ap_dummy_ce,
        if_write_ce => sum_return_V_U_ap_dummy_ce,
        if_din => sum_return_V_din,
        if_full_n => sum_return_V_full_n,
        if_write => sum_return_V_write,
        if_dout => sum_return_V_dout,
        if_empty_n => sum_return_V_empty_n,
        if_read => sum_return_V_read);

    sum_weight_returnSquare_V_U : component FIFO_correlation_accel_v3_sum_weight_returnSquare_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_returnSquare_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_returnSquare_V_U_ap_dummy_ce,
        if_din => sum_weight_returnSquare_V_din,
        if_full_n => sum_weight_returnSquare_V_full_n,
        if_write => sum_weight_returnSquare_V_write,
        if_dout => sum_weight_returnSquare_V_dout,
        if_empty_n => sum_weight_returnSquare_V_empty_n,
        if_read => sum_weight_returnSquare_V_read);

    sum_weight_return_V_U : component FIFO_correlation_accel_v3_sum_weight_return_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_return_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_return_V_U_ap_dummy_ce,
        if_din => sum_weight_return_V_din,
        if_full_n => sum_weight_return_V_full_n,
        if_write => sum_weight_return_V_write,
        if_dout => sum_weight_return_V_dout,
        if_empty_n => sum_weight_return_V_empty_n,
        if_read => sum_weight_return_V_read);

    sum_weight_returnA_returnB_V_U : component FIFO_correlation_accel_v3_sum_weight_returnA_returnB_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_returnA_returnB_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_returnA_returnB_V_U_ap_dummy_ce,
        if_din => sum_weight_returnA_returnB_V_din,
        if_full_n => sum_weight_returnA_returnB_V_full_n,
        if_write => sum_weight_returnA_returnB_V_write,
        if_dout => sum_weight_returnA_returnB_V_dout,
        if_empty_n => sum_weight_returnA_returnB_V_empty_n,
        if_read => sum_weight_returnA_returnB_V_read);

    sum_returnA_V_U : component FIFO_correlation_accel_v3_sum_returnA_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_returnA_V_U_ap_dummy_ce,
        if_write_ce => sum_returnA_V_U_ap_dummy_ce,
        if_din => sum_returnA_V_din,
        if_full_n => sum_returnA_V_full_n,
        if_write => sum_returnA_V_write,
        if_dout => sum_returnA_V_dout,
        if_empty_n => sum_returnA_V_empty_n,
        if_read => sum_returnA_V_read);

    sum_weight_returnSquareA_V_U : component FIFO_correlation_accel_v3_sum_weight_returnSquareA_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_returnSquareA_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_returnSquareA_V_U_ap_dummy_ce,
        if_din => sum_weight_returnSquareA_V_din,
        if_full_n => sum_weight_returnSquareA_V_full_n,
        if_write => sum_weight_returnSquareA_V_write,
        if_dout => sum_weight_returnSquareA_V_dout,
        if_empty_n => sum_weight_returnSquareA_V_empty_n,
        if_read => sum_weight_returnSquareA_V_read);

    sum_weight_returnA_V_U : component FIFO_correlation_accel_v3_sum_weight_returnA_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => sum_weight_returnA_V_U_ap_dummy_ce,
        if_write_ce => sum_weight_returnA_V_U_ap_dummy_ce,
        if_din => sum_weight_returnA_V_din,
        if_full_n => sum_weight_returnA_V_full_n,
        if_write => sum_weight_returnA_V_write,
        if_dout => sum_weight_returnA_V_dout,
        if_empty_n => sum_weight_returnA_V_empty_n,
        if_read => sum_weight_returnA_V_read);

    number_of_days14_channel_U : component FIFO_correlation_accel_v3_number_of_days14_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => number_of_days14_channel_U_ap_dummy_ce,
        if_write_ce => number_of_days14_channel_U_ap_dummy_ce,
        if_din => number_of_days14_channel_din,
        if_full_n => number_of_days14_channel_full_n,
        if_write => number_of_days14_channel_write,
        if_dout => number_of_days14_channel_dout,
        if_empty_n => number_of_days14_channel_empty_n,
        if_read => number_of_days14_channel_read);

    number_of_indices15_channel_U : component FIFO_correlation_accel_v3_number_of_indices15_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => number_of_indices15_channel_U_ap_dummy_ce,
        if_write_ce => number_of_indices15_channel_U_ap_dummy_ce,
        if_din => number_of_indices15_channel_din,
        if_full_n => number_of_indices15_channel_full_n,
        if_write => number_of_indices15_channel_write,
        if_dout => number_of_indices15_channel_dout,
        if_empty_n => number_of_indices15_channel_empty_n,
        if_read => number_of_indices15_channel_read);





    -- ap_reg_procdone_correlation_accel_v3_backEnd_U0 assign process. --
    ap_reg_procdone_correlation_accel_v3_backEnd_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_correlation_accel_v3_backEnd_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_correlation_accel_v3_backEnd_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = correlation_accel_v3_backEnd_U0_ap_done)) then 
                    ap_reg_procdone_correlation_accel_v3_backEnd_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_correlation_accel_v3_frontEnd_U0 assign process. --
    ap_reg_procdone_correlation_accel_v3_frontEnd_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_correlation_accel_v3_frontEnd_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_correlation_accel_v3_frontEnd_U0 <= ap_const_logic_0;
                elsif ((correlation_accel_v3_frontEnd_U0_ap_done = ap_const_logic_1)) then 
                    ap_reg_procdone_correlation_accel_v3_frontEnd_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- correlation_accel_v3_backEnd_U0_ap_start assign process. --
    correlation_accel_v3_backEnd_U0_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                correlation_accel_v3_backEnd_U0_ap_start <= ap_const_logic_0;
            else
                correlation_accel_v3_backEnd_U0_ap_start <= ap_const_logic_1;
            end if;
        end if;
    end process;


    -- ap_CS assign process. --
    ap_CS_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS <= ap_const_logic_0;
        end if;
    end process;
    ap_done <= ap_sig_hs_done;

    -- ap_idle assign process. --
    ap_idle_assign_proc : process(correlation_accel_v3_frontEnd_U0_ap_idle, correlation_accel_v3_backEnd_U0_ap_idle)
    begin
        if (((correlation_accel_v3_frontEnd_U0_ap_idle = ap_const_logic_1) and (ap_const_logic_1 = correlation_accel_v3_backEnd_U0_ap_idle))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_sig_top_allready;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sig_hs_continue <= ap_const_logic_1;

    -- ap_sig_hs_done assign process. --
    ap_sig_hs_done_assign_proc : process(correlation_accel_v3_backEnd_U0_ap_done)
    begin
        if ((ap_const_logic_1 = correlation_accel_v3_backEnd_U0_ap_done)) then 
            ap_sig_hs_done <= ap_const_logic_1;
        else 
            ap_sig_hs_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_sig_top_allready <= correlation_accel_v3_frontEnd_U0_ap_ready;
    correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_dout <= number_of_days14_channel_dout;
    correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_empty_n <= number_of_days14_channel_empty_n;
    correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_dout <= number_of_indices15_channel_dout;
    correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_empty_n <= number_of_indices15_channel_empty_n;
    correlation_accel_v3_backEnd_U0_ap_continue <= ap_sig_hs_continue;
    correlation_accel_v3_backEnd_U0_out_correlation_TREADY <= out_correlation_TREADY;
    correlation_accel_v3_backEnd_U0_sum_returnA_in_V_dout <= sum_returnA_V_dout;
    correlation_accel_v3_backEnd_U0_sum_returnA_in_V_empty_n <= sum_returnA_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_return_in_V_dout <= sum_return_V_dout;
    correlation_accel_v3_backEnd_U0_sum_return_in_V_empty_n <= sum_return_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_in_V_dout <= sum_weight_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_in_V_empty_n <= sum_weight_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_dout <= sum_weight_returnA_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_empty_n <= sum_weight_returnA_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_dout <= sum_weight_returnA_returnB_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_empty_n <= sum_weight_returnA_returnB_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_dout <= sum_weight_returnSquareA_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_empty_n <= sum_weight_returnSquareA_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_dout <= sum_weight_returnSquare_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_empty_n <= sum_weight_returnSquare_V_empty_n;
    correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_dout <= sum_weight_return_V_dout;
    correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_empty_n <= sum_weight_return_V_empty_n;
    correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS <= number_of_days;
    correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_full_n <= number_of_days14_channel_full_n;
    correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES <= number_of_indices;
    correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_full_n <= number_of_indices15_channel_full_n;
    correlation_accel_v3_frontEnd_U0_ap_continue <= ap_const_logic_1;
    correlation_accel_v3_frontEnd_U0_ap_start <= ap_start;
    correlation_accel_v3_frontEnd_U0_in_indices_TDATA <= in_indices_TDATA;
    correlation_accel_v3_frontEnd_U0_in_indices_TDEST <= in_indices_TDEST;
    correlation_accel_v3_frontEnd_U0_in_indices_TID <= in_indices_TID;
    correlation_accel_v3_frontEnd_U0_in_indices_TKEEP <= in_indices_TKEEP;
    correlation_accel_v3_frontEnd_U0_in_indices_TLAST <= in_indices_TLAST;
    correlation_accel_v3_frontEnd_U0_in_indices_TSTRB <= in_indices_TSTRB;
    correlation_accel_v3_frontEnd_U0_in_indices_TUSER <= in_indices_TUSER;
    correlation_accel_v3_frontEnd_U0_in_indices_TVALID <= in_indices_TVALID;
    correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_full_n <= sum_returnA_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_return_out_V_full_n <= sum_return_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_out_V_full_n <= sum_weight_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_full_n <= sum_weight_returnA_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_full_n <= sum_weight_returnA_returnB_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_full_n <= sum_weight_returnSquareA_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_full_n <= sum_weight_returnSquare_V_full_n;
    correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_full_n <= sum_weight_return_V_full_n;
    in_indices_TREADY <= correlation_accel_v3_frontEnd_U0_in_indices_TREADY;
    number_of_days14_channel_U_ap_dummy_ce <= ap_const_logic_1;
    number_of_days14_channel_din <= correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_din;
    number_of_days14_channel_read <= correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_read;
    number_of_days14_channel_write <= correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_write;
    number_of_indices15_channel_U_ap_dummy_ce <= ap_const_logic_1;
    number_of_indices15_channel_din <= correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_din;
    number_of_indices15_channel_read <= correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_read;
    number_of_indices15_channel_write <= correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_write;
    out_correlation_TDATA <= correlation_accel_v3_backEnd_U0_out_correlation_TDATA;
    out_correlation_TDEST <= correlation_accel_v3_backEnd_U0_out_correlation_TDEST;
    out_correlation_TID <= correlation_accel_v3_backEnd_U0_out_correlation_TID;
    out_correlation_TKEEP <= correlation_accel_v3_backEnd_U0_out_correlation_TKEEP;
    out_correlation_TLAST <= correlation_accel_v3_backEnd_U0_out_correlation_TLAST;
    out_correlation_TSTRB <= correlation_accel_v3_backEnd_U0_out_correlation_TSTRB;
    out_correlation_TUSER <= correlation_accel_v3_backEnd_U0_out_correlation_TUSER;
    out_correlation_TVALID <= correlation_accel_v3_backEnd_U0_out_correlation_TVALID;
    sum_returnA_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_returnA_V_din <= correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_din;
    sum_returnA_V_read <= correlation_accel_v3_backEnd_U0_sum_returnA_in_V_read;
    sum_returnA_V_write <= correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_write;
    sum_return_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_return_V_din <= correlation_accel_v3_frontEnd_U0_sum_return_out_V_din;
    sum_return_V_read <= correlation_accel_v3_backEnd_U0_sum_return_in_V_read;
    sum_return_V_write <= correlation_accel_v3_frontEnd_U0_sum_return_out_V_write;
    sum_weight_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_out_V_din;
    sum_weight_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_in_V_read;
    sum_weight_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_out_V_write;
    sum_weight_returnA_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_returnA_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_din;
    sum_weight_returnA_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_read;
    sum_weight_returnA_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_write;
    sum_weight_returnA_returnB_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_returnA_returnB_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_din;
    sum_weight_returnA_returnB_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_read;
    sum_weight_returnA_returnB_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_write;
    sum_weight_returnSquareA_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_returnSquareA_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_din;
    sum_weight_returnSquareA_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_read;
    sum_weight_returnSquareA_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_write;
    sum_weight_returnSquare_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_returnSquare_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_din;
    sum_weight_returnSquare_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_read;
    sum_weight_returnSquare_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_write;
    sum_weight_return_V_U_ap_dummy_ce <= ap_const_logic_1;
    sum_weight_return_V_din <= correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_din;
    sum_weight_return_V_read <= correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_read;
    sum_weight_return_V_write <= correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_write;
end behav;
