// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _correlation_accel_v3_HH_
#define _correlation_accel_v3_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "correlation_accel_v3_frontEnd.h"
#include "correlation_accel_v3_backEnd.h"
#include "FIFO_correlation_accel_v3_sum_weight_V.h"
#include "FIFO_correlation_accel_v3_sum_return_V.h"
#include "FIFO_correlation_accel_v3_sum_weight_returnSquare_V.h"
#include "FIFO_correlation_accel_v3_sum_weight_return_V.h"
#include "FIFO_correlation_accel_v3_sum_weight_returnA_returnB_V.h"
#include "FIFO_correlation_accel_v3_sum_returnA_V.h"
#include "FIFO_correlation_accel_v3_sum_weight_returnSquareA_V.h"
#include "FIFO_correlation_accel_v3_sum_weight_returnA_V.h"
#include "FIFO_correlation_accel_v3_number_of_indices14_channel.h"
#include "FIFO_correlation_accel_v3_number_of_days15_channel.h"

namespace ap_rtl {

struct correlation_accel_v3 : public sc_module {
    // Port declarations 26
    sc_in< sc_lv<32> > number_of_days;
    sc_in< sc_lv<32> > number_of_indices;
    sc_in< sc_lv<32> > in_indices_TDATA;
    sc_in< sc_lv<4> > in_indices_TKEEP;
    sc_in< sc_lv<4> > in_indices_TSTRB;
    sc_in< sc_lv<1> > in_indices_TUSER;
    sc_in< sc_lv<1> > in_indices_TLAST;
    sc_in< sc_lv<1> > in_indices_TID;
    sc_in< sc_lv<1> > in_indices_TDEST;
    sc_out< sc_lv<32> > out_correlation_TDATA;
    sc_out< sc_lv<4> > out_correlation_TKEEP;
    sc_out< sc_lv<4> > out_correlation_TSTRB;
    sc_out< sc_lv<1> > out_correlation_TUSER;
    sc_out< sc_lv<1> > out_correlation_TLAST;
    sc_out< sc_lv<1> > out_correlation_TID;
    sc_out< sc_lv<1> > out_correlation_TDEST;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > in_indices_TVALID;
    sc_out< sc_logic > in_indices_TREADY;
    sc_out< sc_logic > out_correlation_TVALID;
    sc_in< sc_logic > out_correlation_TREADY;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;


    // Module declarations
    correlation_accel_v3(sc_module_name name);
    SC_HAS_PROCESS(correlation_accel_v3);

    ~correlation_accel_v3();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    correlation_accel_v3_frontEnd* correlation_accel_v3_frontEnd_U0;
    correlation_accel_v3_backEnd* correlation_accel_v3_backEnd_U0;
    FIFO_correlation_accel_v3_sum_weight_V* sum_weight_V_U;
    FIFO_correlation_accel_v3_sum_return_V* sum_return_V_U;
    FIFO_correlation_accel_v3_sum_weight_returnSquare_V* sum_weight_returnSquare_V_U;
    FIFO_correlation_accel_v3_sum_weight_return_V* sum_weight_return_V_U;
    FIFO_correlation_accel_v3_sum_weight_returnA_returnB_V* sum_weight_returnA_returnB_V_U;
    FIFO_correlation_accel_v3_sum_returnA_V* sum_returnA_V_U;
    FIFO_correlation_accel_v3_sum_weight_returnSquareA_V* sum_weight_returnSquareA_V_U;
    FIFO_correlation_accel_v3_sum_weight_returnA_V* sum_weight_returnA_V_U;
    FIFO_correlation_accel_v3_number_of_indices14_channel* number_of_indices14_channel_U;
    FIFO_correlation_accel_v3_number_of_days15_channel* number_of_days15_channel_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_ap_start;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_ap_done;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_ap_continue;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_ap_idle;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_ap_ready;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_in_indices_TDATA;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_in_indices_TVALID;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_in_indices_TREADY;
    sc_signal< sc_lv<4> > correlation_accel_v3_frontEnd_U0_in_indices_TKEEP;
    sc_signal< sc_lv<4> > correlation_accel_v3_frontEnd_U0_in_indices_TSTRB;
    sc_signal< sc_lv<1> > correlation_accel_v3_frontEnd_U0_in_indices_TUSER;
    sc_signal< sc_lv<1> > correlation_accel_v3_frontEnd_U0_in_indices_TLAST;
    sc_signal< sc_lv<1> > correlation_accel_v3_frontEnd_U0_in_indices_TID;
    sc_signal< sc_lv<1> > correlation_accel_v3_frontEnd_U0_in_indices_TDEST;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_return_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_return_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_return_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_write;
    sc_signal< sc_lv<32> > correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_din;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_full_n;
    sc_signal< sc_logic > correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_write;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_ap_start;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_ap_done;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_ap_continue;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_ap_idle;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_ap_ready;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_return_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_return_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_return_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_returnA_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_returnA_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_returnA_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_dout;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_empty_n;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_read;
    sc_signal< sc_lv<32> > correlation_accel_v3_backEnd_U0_out_correlation_TDATA;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_out_correlation_TVALID;
    sc_signal< sc_logic > correlation_accel_v3_backEnd_U0_out_correlation_TREADY;
    sc_signal< sc_lv<4> > correlation_accel_v3_backEnd_U0_out_correlation_TKEEP;
    sc_signal< sc_lv<4> > correlation_accel_v3_backEnd_U0_out_correlation_TSTRB;
    sc_signal< sc_lv<1> > correlation_accel_v3_backEnd_U0_out_correlation_TUSER;
    sc_signal< sc_lv<1> > correlation_accel_v3_backEnd_U0_out_correlation_TLAST;
    sc_signal< sc_lv<1> > correlation_accel_v3_backEnd_U0_out_correlation_TID;
    sc_signal< sc_lv<1> > correlation_accel_v3_backEnd_U0_out_correlation_TDEST;
    sc_signal< sc_logic > ap_sig_hs_continue;
    sc_signal< sc_logic > sum_weight_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_V_din;
    sc_signal< sc_logic > sum_weight_V_full_n;
    sc_signal< sc_logic > sum_weight_V_write;
    sc_signal< sc_lv<32> > sum_weight_V_dout;
    sc_signal< sc_logic > sum_weight_V_empty_n;
    sc_signal< sc_logic > sum_weight_V_read;
    sc_signal< sc_logic > sum_return_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_return_V_din;
    sc_signal< sc_logic > sum_return_V_full_n;
    sc_signal< sc_logic > sum_return_V_write;
    sc_signal< sc_lv<32> > sum_return_V_dout;
    sc_signal< sc_logic > sum_return_V_empty_n;
    sc_signal< sc_logic > sum_return_V_read;
    sc_signal< sc_logic > sum_weight_returnSquare_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_returnSquare_V_din;
    sc_signal< sc_logic > sum_weight_returnSquare_V_full_n;
    sc_signal< sc_logic > sum_weight_returnSquare_V_write;
    sc_signal< sc_lv<32> > sum_weight_returnSquare_V_dout;
    sc_signal< sc_logic > sum_weight_returnSquare_V_empty_n;
    sc_signal< sc_logic > sum_weight_returnSquare_V_read;
    sc_signal< sc_logic > sum_weight_return_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_return_V_din;
    sc_signal< sc_logic > sum_weight_return_V_full_n;
    sc_signal< sc_logic > sum_weight_return_V_write;
    sc_signal< sc_lv<32> > sum_weight_return_V_dout;
    sc_signal< sc_logic > sum_weight_return_V_empty_n;
    sc_signal< sc_logic > sum_weight_return_V_read;
    sc_signal< sc_logic > sum_weight_returnA_returnB_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_returnA_returnB_V_din;
    sc_signal< sc_logic > sum_weight_returnA_returnB_V_full_n;
    sc_signal< sc_logic > sum_weight_returnA_returnB_V_write;
    sc_signal< sc_lv<32> > sum_weight_returnA_returnB_V_dout;
    sc_signal< sc_logic > sum_weight_returnA_returnB_V_empty_n;
    sc_signal< sc_logic > sum_weight_returnA_returnB_V_read;
    sc_signal< sc_logic > sum_returnA_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_returnA_V_din;
    sc_signal< sc_logic > sum_returnA_V_full_n;
    sc_signal< sc_logic > sum_returnA_V_write;
    sc_signal< sc_lv<32> > sum_returnA_V_dout;
    sc_signal< sc_logic > sum_returnA_V_empty_n;
    sc_signal< sc_logic > sum_returnA_V_read;
    sc_signal< sc_logic > sum_weight_returnSquareA_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_returnSquareA_V_din;
    sc_signal< sc_logic > sum_weight_returnSquareA_V_full_n;
    sc_signal< sc_logic > sum_weight_returnSquareA_V_write;
    sc_signal< sc_lv<32> > sum_weight_returnSquareA_V_dout;
    sc_signal< sc_logic > sum_weight_returnSquareA_V_empty_n;
    sc_signal< sc_logic > sum_weight_returnSquareA_V_read;
    sc_signal< sc_logic > sum_weight_returnA_V_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > sum_weight_returnA_V_din;
    sc_signal< sc_logic > sum_weight_returnA_V_full_n;
    sc_signal< sc_logic > sum_weight_returnA_V_write;
    sc_signal< sc_lv<32> > sum_weight_returnA_V_dout;
    sc_signal< sc_logic > sum_weight_returnA_V_empty_n;
    sc_signal< sc_logic > sum_weight_returnA_V_read;
    sc_signal< sc_logic > number_of_indices14_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > number_of_indices14_channel_din;
    sc_signal< sc_logic > number_of_indices14_channel_full_n;
    sc_signal< sc_logic > number_of_indices14_channel_write;
    sc_signal< sc_lv<32> > number_of_indices14_channel_dout;
    sc_signal< sc_logic > number_of_indices14_channel_empty_n;
    sc_signal< sc_logic > number_of_indices14_channel_read;
    sc_signal< sc_logic > number_of_days15_channel_U_ap_dummy_ce;
    sc_signal< sc_lv<32> > number_of_days15_channel_din;
    sc_signal< sc_logic > number_of_days15_channel_full_n;
    sc_signal< sc_logic > number_of_days15_channel_write;
    sc_signal< sc_lv<32> > number_of_days15_channel_dout;
    sc_signal< sc_logic > number_of_days15_channel_empty_n;
    sc_signal< sc_logic > number_of_days15_channel_read;
    sc_signal< sc_logic > ap_reg_procdone_correlation_accel_v3_frontEnd_U0;
    sc_signal< sc_logic > ap_sig_hs_done;
    sc_signal< sc_logic > ap_reg_procdone_correlation_accel_v3_backEnd_U0;
    sc_signal< sc_logic > ap_CS;
    sc_signal< sc_logic > ap_sig_top_allready;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_true;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sig_hs_continue();
    void thread_ap_sig_hs_done();
    void thread_ap_sig_top_allready();
    void thread_correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_dout();
    void thread_correlation_accel_v3_backEnd_U0_NUMBER_OF_DAYS_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_dout();
    void thread_correlation_accel_v3_backEnd_U0_NUMBER_OF_INDICES_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_ap_continue();
    void thread_correlation_accel_v3_backEnd_U0_out_correlation_TREADY();
    void thread_correlation_accel_v3_backEnd_U0_sum_returnA_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_returnA_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_return_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_return_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnA_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnA_returnB_in_s_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnSquareA_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_returnSquare_in_V_empty_n();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_dout();
    void thread_correlation_accel_v3_backEnd_U0_sum_weight_return_in_V_empty_n();
    void thread_correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS();
    void thread_correlation_accel_v3_frontEnd_U0_NUMBER_OF_DAYS_out_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES();
    void thread_correlation_accel_v3_frontEnd_U0_NUMBER_OF_INDICES_out_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_ap_continue();
    void thread_correlation_accel_v3_frontEnd_U0_ap_start();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TDATA();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TDEST();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TID();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TKEEP();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TLAST();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TSTRB();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TUSER();
    void thread_correlation_accel_v3_frontEnd_U0_in_indices_TVALID();
    void thread_correlation_accel_v3_frontEnd_U0_sum_returnA_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_return_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_returnA_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_returnA_returnB_out_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_returnSquareA_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_returnSquare_out_V_full_n();
    void thread_correlation_accel_v3_frontEnd_U0_sum_weight_return_out_V_full_n();
    void thread_in_indices_TREADY();
    void thread_number_of_days15_channel_U_ap_dummy_ce();
    void thread_number_of_days15_channel_din();
    void thread_number_of_days15_channel_read();
    void thread_number_of_days15_channel_write();
    void thread_number_of_indices14_channel_U_ap_dummy_ce();
    void thread_number_of_indices14_channel_din();
    void thread_number_of_indices14_channel_read();
    void thread_number_of_indices14_channel_write();
    void thread_out_correlation_TDATA();
    void thread_out_correlation_TDEST();
    void thread_out_correlation_TID();
    void thread_out_correlation_TKEEP();
    void thread_out_correlation_TLAST();
    void thread_out_correlation_TSTRB();
    void thread_out_correlation_TUSER();
    void thread_out_correlation_TVALID();
    void thread_sum_returnA_V_U_ap_dummy_ce();
    void thread_sum_returnA_V_din();
    void thread_sum_returnA_V_read();
    void thread_sum_returnA_V_write();
    void thread_sum_return_V_U_ap_dummy_ce();
    void thread_sum_return_V_din();
    void thread_sum_return_V_read();
    void thread_sum_return_V_write();
    void thread_sum_weight_V_U_ap_dummy_ce();
    void thread_sum_weight_V_din();
    void thread_sum_weight_V_read();
    void thread_sum_weight_V_write();
    void thread_sum_weight_returnA_V_U_ap_dummy_ce();
    void thread_sum_weight_returnA_V_din();
    void thread_sum_weight_returnA_V_read();
    void thread_sum_weight_returnA_V_write();
    void thread_sum_weight_returnA_returnB_V_U_ap_dummy_ce();
    void thread_sum_weight_returnA_returnB_V_din();
    void thread_sum_weight_returnA_returnB_V_read();
    void thread_sum_weight_returnA_returnB_V_write();
    void thread_sum_weight_returnSquareA_V_U_ap_dummy_ce();
    void thread_sum_weight_returnSquareA_V_din();
    void thread_sum_weight_returnSquareA_V_read();
    void thread_sum_weight_returnSquareA_V_write();
    void thread_sum_weight_returnSquare_V_U_ap_dummy_ce();
    void thread_sum_weight_returnSquare_V_din();
    void thread_sum_weight_returnSquare_V_read();
    void thread_sum_weight_returnSquare_V_write();
    void thread_sum_weight_return_V_U_ap_dummy_ce();
    void thread_sum_weight_return_V_din();
    void thread_sum_weight_return_V_read();
    void thread_sum_weight_return_V_write();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
